# Generated by Django 6.1.1 on 2026-09-30 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ressources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_compt', models.PositiveIntegerField(blank=True, null=True)),
                ('last_compt', models.PositiveIntegerField(blank=True, null=True)),
                ('compt_act', models.PositiveIntegerField(blank=True, null=True)),
                ('date_compt', models.DateTimeField(auto_now_add=True)),
                ('ecart', models.PositiveIntegerField(blank=True, null=True)),
                ('statut_compt', models.CharField(choices=[('USUEL', 'USUEL'), ('EP', 'EP')], default='USUEL', max_length=15)),
                ('user_compt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compteur_user', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicule_compteur', to='Ressources.vehicules')),
            ],
        ),
    ]
