# Generated by Django 6.1.1 on 2026-10-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compteurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteur',
            name='ecart',
            field=models.FloatField(),
        ),
    ]
