# Generated by Django 6.1.1 on 2026-09-30 07:22

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSheet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='EMAIL')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='MOT DE PASSE')),
                ('first_name', models.CharField(blank=True, max_length=240, verbose_name='PRENOM')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='NOM')),
                ('mobile', models.CharField(blank=True, max_length=255, verbose_name='N° TELEPHONE')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='ADRESSE')),
                ('fonction', models.CharField(blank=True, max_length=255, null=True, verbose_name='POSTE')),
                ('type', models.CharField(max_length=50, verbose_name='TYPE PERSONNEL')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Région')),
                ('site', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site')),
                ('is_staff', models.BooleanField(default=True, verbose_name='STAFF')),
                ('is_active', models.BooleanField(default=True, verbose_name='ACTIF')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='SUPER UTILISATEUR')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Vehicules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('nparc', models.CharField(blank=True, max_length=20, null=True)),
                ('noptim', models.CharField(blank=True, max_length=20, null=True)),
                ('immat', models.CharField(blank=True, max_length=20, null=True)),
                ('nature', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('marque', models.CharField(blank=True, max_length=50, null=True)),
                ('modele', models.CharField(blank=True, max_length=50, null=True)),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('energie', models.CharField(blank=True, max_length=20, null=True)),
                ('puissance', models.CharField(blank=True, max_length=15, null=True)),
                ('type_compt', models.CharField(choices=[('H', 'H'), ('KM', 'KM')], max_length=10)),
                ('annee_mes', models.CharField(blank=True, max_length=20, null=True)),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
                ('affectation', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.CharField(blank=True, max_length=20, null=True)),
                ('responsable_sabc', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_compt', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id_newuser', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Email invalide')])),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=240)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, choices=[('OPERATEUR', 'OPERATEUR'), ('CHEF_ZONE', 'CHEF_ZONE'), ('CHEF_ATELIER', 'CHEF_ATELIER'), ('CHEF_AGENCE', 'CHEF_AGENCE'), ('MASTER_DATA', 'MASTER_DATA'), ('DIRECTEUR', 'DIRECTEUR')], max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('fonction', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
