# Generated by Django 6.1.1 on 2026-09-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compt', models.PositiveIntegerField(blank=True, null=True)),
                ('date_compt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanningEp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compt_ep', models.PositiveIntegerField(blank=True, null=True)),
                ('date_recept', models.DateField()),
                ('date_ent', models.DateField()),
                ('type_ep', models.CharField(max_length=15)),
                ('etat', models.CharField(choices=[('EFFECTUE', 'EFFECTUE'), ('NON EFFECTUE', 'NON EFFECTUE')], default='NON EFFECTUE', max_length=15)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'PLANIFIE'), ('NON PLANIFIE', 'NON PLANIFIE')], default='PLANIFIE', max_length=15)),
                ('numbt', models.CharField(blank=True, max_length=20, null=True)),
                ('observation', models.CharField(blank=True, choices=[('', ''), ('ENGIN PAS LIBERE', 'ENGIN PAS LIBERE'), ('COMPTEUR NON ECHU', 'COMPTEUR NON ECHU'), ('ENGIN EN PANNE', 'ENGIN EN PANNE')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviEp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_ep', models.CharField(blank=True, choices=[('250 H', '250 H'), ('500 H', '500 H'), ('750 H', '750 H'), ('1000 H', '1000 H'), ('1250 H', '1250 H'), ('1500 H', '1500 H'), ('1750 H', '1750 H'), ('2000 H', '2000 H'), ('', ''), ('5000 KM', '5000 KM'), ('10000 KM', '10000 KM'), ('15000 KM', '15000 KM'), ('20000 KM', '20000 KM'), ('25000 KM', '25000 KM'), ('30000 KM', '30000 KM'), ('', ''), ('150 H', '150 H'), ('300 H', '300 H'), ('450 H', '450 H'), ('600 H', '600 H'), ('750 H', '750 H'), ('900 H', '900 H'), ('1050 H', '1050 H'), ('1200 H', '1200 H')], max_length=10, null=True)),
                ('date_last_ep', models.DateField(blank=True, max_length=30, null=True)),
                ('cpt_last_ep', models.PositiveIntegerField()),
                ('cpt_next_ep', models.PositiveIntegerField()),
                ('cpt_actuel', models.PositiveIntegerField()),
                ('ecart', models.FloatField()),
                ('statut', models.CharField(blank=True, choices=[('RAS', 'RAS'), ('A VIDANGER', 'A VIDANGER'), ('EN DEPASSEMENT', 'EN DEPASSEMENT')], max_length=30, null=True)),
                ('program_ep', models.CharField(blank=True, choices=[('250 H', '250 H'), ('500 H', '500 H'), ('750 H', '750 H'), ('1000 H', '1000 H'), ('1250 H', '1250 H'), ('1500 H', '1500 H'), ('1750 H', '1750 H'), ('2000 H', '2000 H'), ('', ''), ('5000 KM', '5000 KM'), ('10000 KM', '10000 KM'), ('15000 KM', '15000 KM'), ('20000 KM', '20000 KM'), ('25000 KM', '25000 KM'), ('30000 KM', '30000 KM'), ('', ''), ('150 H', '150 H'), ('300 H', '300 H'), ('450 H', '450 H'), ('600 H', '600 H'), ('750 H', '750 H'), ('900 H', '900 H'), ('1050 H', '1050 H'), ('1200 H', '1200 H')], max_length=20, null=True)),
                ('bt', models.CharField(blank=True, max_length=30, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
