# Generated by Django 6.1.1 on 2026-09-30 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Preventive', '0001_initial'),
        ('Ressources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='user_compt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compteur_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compteur',
            name='veh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compteur_veh', to='Ressources.vehicules'),
        ),
        migrations.AddField(
            model_name='planningep',
            name='veh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_veh', to='Ressources.vehicules'),
        ),
        migrations.AddField(
            model_name='suiviep',
            name='veh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivi_veh', to='Ressources.vehicules'),
        ),
    ]
