# Generated by Django 6.1.1 on 2026-09-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preventive', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compteur',
        ),
    ]
