# Generated by Django 6.1.1 on 2026-10-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventive', '0003_delete_compteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiviep',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Région'),
        ),
    ]
