# Generated by Django 6.1.1 on 2026-10-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preventive', '0004_suiviep_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suiviep',
            old_name='veh',
            new_name='vehicule',
        ),
    ]
