# Generated by Django 6.1.1 on 2026-10-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preventive', '0005_rename_veh_suiviep_vehicule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suiviep',
            name='ecart',
        ),
        migrations.RemoveField(
            model_name='suiviep',
            name='statut',
        ),
    ]
